### ISSUE TITLE
`my.colors()` not defined

### ISSUE THREAD

**Issue by setgree** [kjhealy/nces-degrees#1]
Is this part of your `.rprofile?`

My apologies if this is something about R I am not understanding. 

I came across this via Twitter (https://twitter.com/familyunequal/status/981563693979889665), looks great!

**Comment by kjhealy** [comment]
Whoops; a function from my own utility library. I've added it in  https://github.com/kjhealy/nces-degrees/commit/28384b45898b9ea54ac4ef84aed8803959476941 (and changed the name to `my_colors()` for consistency with the rest of the code).
